from django.conf import settings
import os
import boto3


def s3_client():
    session = boto3.session.Session()
    client = session.client('s3', region_name=os.getenv('AWS_S3_REGION'),
                            endpoint_url=os.getenv('AWS_S3_ENDPOINT_URL_WITHOUT_BUCKET_NAME'),
                            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
                            )
    return client


def get_contents(path):
    """
    Retrieving the objects from the bucket.
    :param path: object path.
    :return: result dict.
    """
    client = s3_client()
    result = client.list_objects(Bucket=f'{os.getenv("AWS_S3_BUCKET_NAME")}',
                                 Prefix=f'{path}', Delimiter='/')
    folders = []
    files = []
    details = {}
    contents = {'folders': folders, 'files': files}

    data = {'details': details, 'contents': contents}

    if result:
        if result.get('Contents'):
            for content in result.get('Contents'):
                if content.get('Key') != path:
                    name = content.get('Key').replace(os.getenv("AWS_S3_ROOT_DIRECTORY"), '')
                    file = {'path': name, 'name': name.split('/')[-1]}
                    files.append(file)
                else:
                    # Avoiding any folders.
                    if content.get('Key')[-1] != '/':
                        url = client.generate_presigned_url('get_object',
                                                            Params={'Bucket': f'{os.getenv("AWS_S3_BUCKET_NAME")}',
                                                                    'Key': f'{path}'}, ExpiresIn=100)
                        details = {'path': path, 'name': path.split('/')[-1], 'size': content.get('Size'), 'url': url}
                        data['details'] = details

            # Checking for other folders
            if result.get('CommonPrefixes'):
                for prefix in result.get('CommonPrefixes'):
                    folder_name = prefix['Prefix'].replace(os.getenv("AWS_S3_ROOT_DIRECTORY"), '')
                    folder_name_formatted = folder_name.split('/')
                    if len(folder_name_formatted) >= 2:
                        folder_name_formatted = folder_name_formatted[-2]
                    else:
                        folder_name_formatted = folder_name_formatted[0]
                    folder = {'path': folder_name, 'name': folder_name_formatted}
                    folders.append(folder)
    return data


def restructure_errors(errors):
    """
    A function for re-structuring the serializing errors send by the DRF itself.
    :param errors: Errors generated by the Rest Framework.
    :return: Re-structured list of errors.
    """
    list_of_errors = []
    for field, errors in errors.items():
        field_errors = []
        for error in errors:
            field_errors.append(error)
        list_of_errors.append({'field': field, 'errors': field_errors})
    return list_of_errors
